
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btxnyuqgwfcvsxdolnjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0eG55dXFnd2ZjdnN4ZG9sbmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjI1NjAsImV4cCI6MjA2MTgzODU2MH0.bAry66eRRlprbW7NFVxZLoq2XDlDgyWOvojKSeAJgrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true
    }
  }
);
